/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaGUI */

#ifndef _Included_JavaGUI
#define _Included_JavaGUI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaGUI
 * Method:    searchByName
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_JavaGUI_searchByName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JavaGUI
 * Method:    searchByBirth
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_JavaGUI_searchByBirth
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     JavaGUI
 * Method:    insert
 * Signature: (JLjava/lang/String;Ljava/lang/String;IIIZLjava/lang/String;ZIII)J
 */
JNIEXPORT jlong JNICALL Java_JavaGUI_insert
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint, jint, jboolean, jstring, jboolean, jint, jint, jint);

/*
 * Class:     JavaGUI
 * Method:    convertToTree
 * Signature: (J)LJavaGUI/TNode;
 */
JNIEXPORT jobject JNICALL Java_JavaGUI_convertToTree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JavaGUI
 * Method:    modify
 * Signature: (JLjava/lang/String;IIIZLjava/lang/String;ZIII)J
 */
JNIEXPORT jlong JNICALL Java_JavaGUI_modify
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jint, jboolean, jstring, jboolean, jint, jint, jint);

/*
 * Class:     JavaGUI
 * Method:    sortByBirth
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JavaGUI_sortByBirth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JavaGUI
 * Method:    modifyDate
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_JavaGUI_modifyDate
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     JavaGUI
 * Method:    remindBirth
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JavaGUI_remindBirth
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     JavaGUI
 * Method:    convertToDate
 * Signature: (J)LJavaGUI/Date;
 */
JNIEXPORT jobject JNICALL Java_JavaGUI_convertToDate
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
